version: '3.8'
services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backbone-app
        image: backbone-app:latest
        working_dir: /var/www/
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
        ports:
            - 8088:80
        env_file:
            - .env
        environment:
            CONTAINER_ROLE: app
            DB_CONNECTION: mysql
            DB_HOST: database
            DB_PORT: 33061
            DB_DATABASE: backboneinternal
            DB_USERNAME: root
            DB_PASSWORD: some_pass
        networks:
            - app-network
        depends_on:
            - database
    database:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "33061:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - ./initdb.sql:/data/application/initdb.sql
        command: --init-file /data/application/initdb.sql
        environment:
            MYSQL_ROOT_PASSWORD: some_pass
            MYSQL_DATABASE: backboneinternal
            CONTAINER_ROLE: db
        networks:
            - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
